---
title: "Flexdashboard"
---

```{r}
library(tidyverse)
library(viridis)
library(plotly)
library(readr)
```


```{r}

library(p8105.datasets)
data("instacart")

instacart %>% 
  janitor::clean_names()

# Create boxplot comparing order hour of day of fresh vs. frozen items
instacart %>% 
  filter(str_detect(aisle, "frozen|fresh ")) %>% 
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) %>% 
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box", colors = "Set2")

instacart %>% 
  filter(aisle == "fresh vegetables") %>% 
  mutate(order_dow = as.character(order_dow),
         order_dow = fct_reorder(order_dow, order_hour_of_day)) %>% 
  plot_ly(y = ~order_hour_of_day, color = ~order_dow, type = "box", 
          colors = "Set2") 

top_aisles = instacart %>% 
  count(aisle, sort = TRUE) %>% 
  top_n(10) %>% 
  select(aisle)

inner_join(instacart, top_aisles,
             by = "aisle") %>% 
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) %>% 
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box", colors = "Set2")



```

```{r}

instacart %>%
  group_by(aisle) %>%
  summarize(n = n()) %>%
  arrange(-n) %>% 
  top_n(10) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar")
```

```{r}

instacart %>% 
  filter(str_detect(aisle, "fresh ")) %>% 
  select(aisle, order_dow, order_hour_of_day) %>% 
  arrange(aisle, order_dow) %>% 
  group_by(aisle, order_dow) %>% 
  mutate(mean_hour = mean(order_hour_of_day)) %>% 
  plot_ly(x = ~order_dow, y = ~mean_hour, type = "scatter", mode = "line", color = ~aisle)
```


